volumes:
  sql_db:

services:
  nginx:
    image: nginx:alpine
    restart: always
    depends_on:
      - maven_app
    ports:
      - 80:80
    volumes:
      - ./src/main/webapp:/etc/nginx/statics
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - front

  mysql_db:
    image: mysql:5.7.40-debian
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: lavagna
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=pass --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 1s
      retries: 20
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - sql_db:/var/lib/mysql
    networks:
      - back

  maven_app:
    container_name: maven_app
    build: .
    restart: always
    depends_on:
      mysql_db:
        condition: service_healthy
    networks:
      - front
      - back

  documentation:
    build: 
      context: .
      dockerfile: Dockerfile.docu
    restart: always
    depends_on:
      - nginx
    ports:
      - 8081:45001

networks:
  front:
  back: