volumes:
  db_data:

services:
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: mysql:5.7
    command:
      - mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      - mysql -u root -e 'CREATE DATABASE lavagna CHARACTER SET utf8 COLLATE utf8_bin;'
    ports:
      - 3306:3360
    volumes:
      - db_data:/var/lib/mysql/
      - ./src/main/resources/io/lavagna/db/MYSQL:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: lavagna
      MYSQL_USER: sa
      MYSQL_PASSWORD: superpass
      MYSQL_ROOT_PASSWORD: superpass
    # networks:
    #   - back-end


  
  