FROM maven:3.6.3-jdk-8 as builder

WORKDIR /stampo

COPY ./misc ./misc
COPY ./puppet ./puppet
COPY ./src ./src
COPY ./.editorconfig .
COPY ./.eslintrc .
COPY ./.travis.yml .
COPY ./generate-material.js .
COPY ./package.json .
COPY ./LICENSE-GPLv3.txt .
COPY ./Vagrantfile .
COPY ./pom.xml .


RUN mvn clean stampo:build

ENTRYPOINT [ "mvn", "stampo:serve" ]